file vmlinux
set backtrace limit 20
b remap_pfn_range
#b early_init_dt_scan_memory
#b map_lowmem
#b prepare_page_table
#b build_zonelists
#b memmap_init
#b memmap_init_zone
#b __free_pages_bootmem
#b alloc_init_pte
#b arm_pte_alloc
#b smp_setup_processor_id
#b start_kernel
#b alloc_thread_stack_node
#b current_thread_info
#b do_DataAbort
#b do_page_fault
#b do_anonymous_page
#b do_fault
#b do_swap_page
#b do_wp_page
#b find_pid_ns
#b find_vpid
#b find_get_pid
#b _do_fork
#b sys_fork
#b sys_vfork
#b smp_init
#b arm_dt_init_cpu_maps
#b smp_prepare_cpus
#b sched_init_domains
#init_task
#b context_switch
#b switch_to
#b __switch_to
#b arm_dt_init_cpu_maps
#b sched_init_domains